
services:
  build-frontend:
    image: node:18
    working_dir: /client
    volumes:
      - ./client:/client
    command: sh -c "npm install && npm run build"
    depends_on: []

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./client/dist:/app/dist
    depends_on:
      build-frontend:
        condition: service_completed_successfully