/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Survivor } from "./Survivor";
import {
  SurvivorFromJSON,
  SurvivorFromJSONTyped,
  SurvivorToJSON,
  SurvivorToJSONTyped,
} from "./Survivor";

/**
 *
 * @export
 * @interface CreateSurvivorRequest
 */
export interface CreateSurvivorRequest {
  /**
   *
   * @type {Survivor}
   * @memberof CreateSurvivorRequest
   */
  survivor: Survivor;
  /**
   *
   * @type {{ [key: string]: number; }}
   * @memberof CreateSurvivorRequest
   */
  itemTypeAndAmountDict: { [key: string]: number };
}

/**
 * Check if a given object implements the CreateSurvivorRequest interface.
 */
export function instanceOfCreateSurvivorRequest(
  value: object,
): value is CreateSurvivorRequest {
  if (!("survivor" in value) || value["survivor"] === undefined) return false;
  if (
    !("itemTypeAndAmountDict" in value) ||
    value["itemTypeAndAmountDict"] === undefined
  )
    return false;
  return true;
}

export function CreateSurvivorRequestFromJSON(
  json: any,
): CreateSurvivorRequest {
  return CreateSurvivorRequestFromJSONTyped(json, false);
}

export function CreateSurvivorRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateSurvivorRequest {
  if (json == null) {
    return json;
  }
  return {
    survivor: SurvivorFromJSON(json["survivor"]),
    itemTypeAndAmountDict: json["item_type_and_amount_dict"],
  };
}

export function CreateSurvivorRequestToJSON(json: any): CreateSurvivorRequest {
  return CreateSurvivorRequestToJSONTyped(json, false);
}

export function CreateSurvivorRequestToJSONTyped(
  value?: CreateSurvivorRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    survivor: SurvivorToJSON(value["survivor"]),
    item_type_and_amount_dict: value["itemTypeAndAmountDict"],
  };
}
