/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SurvivorListReply
 */
export interface SurvivorListReply {
    /**
     * 
     * @type {Array<Array<any>>}
     * @memberof SurvivorListReply
     */
    survivorsWithReported: Array<Array<any>>;
}

/**
 * Check if a given object implements the SurvivorListReply interface.
 */
export function instanceOfSurvivorListReply(value: object): value is SurvivorListReply {
    if (!('survivorsWithReported' in value) || value['survivorsWithReported'] === undefined) return false;
    return true;
}

export function SurvivorListReplyFromJSON(json: any): SurvivorListReply {
    return SurvivorListReplyFromJSONTyped(json, false);
}

export function SurvivorListReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SurvivorListReply {
    if (json == null) {
        return json;
    }
    return {
        
        'survivorsWithReported': json['survivors_with_reported'],
    };
}

export function SurvivorListReplyToJSON(json: any): SurvivorListReply {
    return SurvivorListReplyToJSONTyped(json, false);
}

export function SurvivorListReplyToJSONTyped(value?: SurvivorListReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'survivors_with_reported': value['survivorsWithReported'],
    };
}

